twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    #form_themes: ['bootstrap_4_Horizontal_layout.html.twig']
    globals:
        appName: 'Talengo.io'
        appEmail: 'talengo.contact@gmail.com'
        appPhone: '06 51 80 44 37'
        currency: ' €'
        ashtag: '#'
        appConcepteur: "Najim Conception"
        app_environement: '%env(APP_ENV)%'
        stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
        map_box_token: '%env(MAPBOX_TOKEN)%'
        appSite: 'https://talengo.io/'
        appSiteLocal: 'https://127.0.0.1:8000/'

when@test:
    twig:
        strict_variables: true
